import {
  campaignListings,
  monthlyYield,
  weeklyYield,
  passingYield,
  type AxtraCampaign,
} from "./axtraFactory";

const pack = {
  week: "https://www.dropbox.com/scl/fo/1dt03qqksd5kk7fr8yeiy/AE-xUXEJ9L6b9PZAwQkCQcQ?rlkey=qslz9i8aakfadvc7eijx9w6ts&dl=0",
  sodurlund: "https://www.dropbox.com/scl/fo/r67peo72fgcv6o643mpci/ACiMLnlxCYOWHdj6UYar-xo?rlkey=d0lb5h5rkrjd7aen5gnmikejs&dl=0",
  aldo: "https://www.dropbox.com/scl/fo/o6jod55nbni4z9texw0c6/ANrrdE5hL5YidzU2_nYLjYM?rlkey=x3oevz644de1vydlvalw1avam&dl=0",
  almray: "https://www.dropbox.com/scl/fo/ovkzchfvortzsdtxfm47k/AEfi15RAMakYb4HMJJmW1sA?rlkey=3pdcwvnh0rzlrvgnvg4b1uvqz&dl=0",
  vine: "https://www.dropbox.com/scl/fo/7qcm0tjbhqjd78k84ods6/AOxuNP4AXrFzuvldNuvRH4E?rlkey=g93f5tmg5p4lipuswly59p01u&dl=0",
  waverley: "https://www.dropbox.com/scl/fo/c7ni541c0p5q8o5wqxt4q/AM33gjdgMqVljQhJKI1p3zQ?rlkey=s9gfzprr3juovu47q2vrumxqo&dl=0",
  eildon: "https://www.dropbox.com/scl/fo/puv4k67shozcbp8xarp63/AIwnVjyRma1cG1uVAk6KEs8?rlkey=v72kq3iv6fm8im32d60b3bp2h&dl=0",
  westall: "https://www.dropbox.com/scl/fo/5jptusfn4at0hf3b1wxj8/AIzUBiUR-G6XL79_2FNP7yg?rlkey=jk9x0ti3gqmumgpidq0p77wmc&dl=0",
  lyra: "https://www.dropbox.com/scl/fo/x1gj6d5in3en32musffln/ANTnhVW4c1kk5JZs95RluEg?rlkey=886dg5l5h3mbk6wh6zab8wwwi&dl=0",
  joyhill: "https://www.dropbox.com/scl/fo/hqzr6lgrxf9n69nudp9n8/ABlhWmPVetzOqZUlQ2ePzAo?rlkey=2woi896m6afl5zyf845k9i2l8&dl=0",
  christina: "https://www.dropbox.com/scl/fo/zb49xtfzgnp2rsn6rbagl/ANI-j_Bg7GHFcZNhDIiSs_0?rlkey=lt1z6r47f79wb0kgm2jq22vjt&dl=0",
  davis: "https://www.dropbox.com/scl/fo/ouawn2ntro3su42abqoec/AILcX3a8GXlXfeTVOHYsZ0E?rlkey=peo1ejsijfelqb7st18tgcgqi&dl=0",
  mcmillan: "https://www.dropbox.com/scl/fo/co9glmxpgo2hbwwfiyv1a/AFOk87lGuYacpohoILQHxQ8?rlkey=xiad4i39qnd60vu4u4zbcqz0o&dl=0",
  nelson: "https://www.dropbox.com/scl/fo/nuilanqzv3sn33nsz9wem/AHpmA4AQ6k-otZpa6jnU8Ec?rlkey=wcjocnrxecurpfe3rra5l6bk8&dl=0",
  sunrise: "https://www.dropbox.com/scl/fo/o51iwbl9ncn91bo6ess7c/AHE5Vu9DEhClNNPcqC6gJsU?rlkey=prpwkgw7b1p7l0fmzkfehyojf&dl=0",
  walker: "https://www.dropbox.com/scl/fo/3sid2n2g1wuf9y0j28ged/AJwFzF7um7dEBw_zgAKvwX0?rlkey=2lmzwyoapfuqw0uvgqy8bu813&dl=0",
  manningham: "https://www.dropbox.com/scl/fo/9wodz7mlalx9hy3zeuhrb/AMbjBYjJhcbfNx38vX0m5_o?rlkey=agiavj9imp5ilfvbcziloxss1&dl=0",
  major: "https://www.dropbox.com/scl/fo/1l5htn4wj36nmyojzmyi5/AANehY3G1Pv2GUY0bBK7Tjs?rlkey=9p9ch6v3u1qytpvcw673bic3t&dl=0",
  mercury: "https://www.dropbox.com/scl/fo/bddmwhk47wa2asoqbgbzs/AEChyV_MTnO0wVCQiGUP0vI?rlkey=y9p5jcvr3agtlw7uqrxchzc0u&dl=0",
  parkglen: "https://www.dropbox.com/scl/fo/yv76c1i4n0euiqgbdyqck/AB8p6eoUx_iuGrLrfIqYiD8?rlkey=9co2nt2rm98rysvi5yzrba84j&dl=0",
  wingate: "https://www.dropbox.com/scl/fo/h8rlk91mp735sb37c82ji/AKSRfkFWQlAuyOJoiS5JNvM?rlkey=tzd5ir9pjf5gtko5offjfp3u2&dl=0",
  rosella: "https://www.dropbox.com/scl/fo/p4rgfom9z5uhwydvx4q9u/ALbaecp36MSufwrpjkuzEnM?rlkey=xd1txxu06rxepesptq7ov2ork&dl=0",
  pitt: "https://www.dropbox.com/scl/fo/ktgt7qf1qizruvw49u34m/AIYcGQqL0i-TEraFiVTe6pk?rlkey=bmht9guobwmytnij527k0mexp&dl=0",
  riverwalk: "https://www.dropbox.com/scl/fo/f2llkq7b1gyob132y717b/AI7cMHAKkAYD7AKeA3hlDHk?rlkey=kzd2nxao52fovfkihl7chuc6y&dl=0",
  winfield: "https://www.dropbox.com/scl/fo/8094gz6l8m4duc22s28ez/AJcnNOYP1aIOVNLOLvo8lwY?rlkey=4f83p2d87wmz14d7zgppqwp1y&dl=0",
  laurel: "https://www.dropbox.com/scl/fo/xh57hjirk1j0nxc8r5y23/AGxOyIqcf-drnypYM8xDNxA?rlkey=pbhdzqhobsehbg4dzewgaalwt&dl=0",
  thompsons: "https://www.dropbox.com/scl/fo/gj8sa118rx91wu2bbzlee/AMiJTzM8yoQyce0JccIuRCY?rlkey=86kbaz5hypmlw80c05ewwvesk&dl=0",
  travers: "https://www.dropbox.com/scl/fo/hl9q5v0r5gpligque4wjh/ADq0fjei6vDuBiIpuR8RI9k?rlkey=6n34d5t80nfyu9qc6jgzjlxr6&dl=0",
  willowstone: "https://www.dropbox.com/scl/fo/hcijoo7xefdbeijq9vc2i/AOB4uzlaej05879CjRiOgMA?rlkey=2v8ireab2nhp31jap5yeaxppx&dl=0",
  hull: "https://www.dropbox.com/scl/fo/6re4qfqbvq9j0azu6y2oi/AJLq_FdgwLSZQJY-NHDf37A?rlkey=bzq0wx76nc155nathp0x7ilc3&dl=0",
  spring: "https://www.dropbox.com/scl/fo/zkmm82iiyhf9cdgn4hzvz/AJYkqj0ORXCoiuIS2kM-9Hk?rlkey=6pcxjyg3da4jzlc7lxoh8dyvt&dl=0",
  eden: "https://www.dropbox.com/scl/fo/gg4jjfxivggx7b2piuyvb/AKK2fhSmEhAicQ113JqpCpo?rlkey=aafkvyp8d0pkyumu0iezjxbx7&dl=0",
  finlay: "https://www.dropbox.com/scl/fo/3yegapp5hn0ii6nvw7par/APuEn6EyGUJR9G6k1FicM4s?rlkey=ro38z03adgbos83r770ywh0rf&dl=0",
  northern: "https://www.dropbox.com/scl/fo/1sn387m5o8rmlhgdt2fbh/AL6AF8tqoB4IvxdXImXzO5o?rlkey=i5mrybs4nz3rmoajc2w2z66ih&dl=0",
  plenty: "https://www.dropbox.com/scl/fo/5e12yjoixqf6mrov6bktn/AONbLg7A5FK5MsEGnJtf-Ws?rlkey=z3c4chdzke1iko37zauq02z1w&dl=0",
  norman: "https://www.dropbox.com/scl/fo/s40tsoyor7bjzva912qcj/AKJBu4Iu0B260pwwLLvrJiY?rlkey=6qmbk1dh78fwlrpup3w9ohzdd&dl=0",
  clingin: "https://www.dropbox.com/scl/fo/y854w9lzhac7qvd49l1so/AB8AnIS7-uFDcTZwWaVBRS8?rlkey=ryduqv5dp9qv3nizchjqmhecd&dl=0",
  rosebud: "https://www.dropbox.com/scl/fo/ltwzcj9t4gk76z5m2svkn/AORLzhri49-qZdlNko-XiK4?rlkey=b7tqggnbti0d1ltzl077tgbxw&dl=0",
  corio: "https://www.dropbox.com/scl/fo/40l5qspnvinq4ml9rjsq8/AEtUVvNcTToiENRwx0q5xnk?rlkey=xa16lz9wxnxrifc8ck0dkmyya&dl=0",
  sparrowhawk: "https://www.dropbox.com/scl/fo/yx6y1zplns6qwszuu3tmu/AEIcRNZwIlvVA_kBda-dHiM?rlkey=g41kpazcffwgh6g0u2xdfyzlb&dl=0",
  ceduna: "https://www.dropbox.com/scl/fo/lgozqzx624mznvccin3rx/AA88WnIwATCLfLUrKzr5Cls?rlkey=738pzcw6o8mfw3oep5dm5qjw6&dl=0",
  launceston: "https://www.dropbox.com/scl/fo/t48v8ei5uxam49izu60hf/AOtwfBntM93FzJcGtBt1-t4?rlkey=ilsg48gg6772um7a7umuoyf16&dl=0",
  leakes: "https://www.dropbox.com/scl/fo/fzegfiweh6b9q34je6fxb/APwRowDSGS9EyF8ISnRyjDc?rlkey=4abe9err7v7cyc26zjkc1jmnv&dl=0",
  cardross: "https://www.dropbox.com/scl/fo/qyobtvbssh1cb2fq7kwzv/AL6_zxGFGQ6AAHHa2rcgLl0?rlkey=g9x4ndh1jb7987uqetuc5518h&dl=0",
} as const;

function c(partial: AxtraCampaign): AxtraCampaign {
  return partial;
}

export const AXTRA_LISTINGS = [
  ...campaignListings(
    c({
      suburb: "Mitcham",
      postcode: "3132",
      type: "townhouse",
      firb: "YES",
      completion: "Q4 2026",
      primary: "Rangeview Primary School",
      secondary: "Mullauna Secondary College",
      commission: "3.3% inc GST, payment term 50/50",
      pack: pack.week,
      extraCampaign: "Project of the week on the current Axtra list.",
    }),
    [
      {
        slug: "26-dudley-street-mitcham-unit-1",
        address: "Unit 1, 26 Dudley Street",
        price: 1450000,
        floor: 154.21,
        beds: 4,
        baths: 3,
        cars: 2,
        carNote: "1 + 1",
        specNote: "Two living areas.",
        promo: "Limited-time campaign offer: $20,000 cash rebate (confirm terms in writing).",
      },
      {
        slug: "26-dudley-street-mitcham-unit-2",
        address: "Unit 2, 26 Dudley Street",
        price: 1360000,
        floor: 162.73,
        beds: 4,
        baths: 3,
        cars: 2,
        specNote: "Two living areas.",
      },
      {
        slug: "26-dudley-street-mitcham-unit-3",
        address: "Unit 3, 26 Dudley Street",
        price: 1250000,
        floor: 159.13,
        beds: 3,
        baths: 3,
        cars: 2,
        carNote: "carport plus extra space",
        specNote: "Two living areas.",
      },
    ],
  ),

  ...campaignListings(
    c({
      suburb: "Doncaster",
      postcode: "3108",
      type: "house",
      firb: "NO",
      completion: "Established house",
      primary: "Templestowe Heights Primary School",
      secondary: "Templestowe College",
      commission: "$50,000 inc GST, payment at settlement",
      pack: pack.sodurlund,
    }),
    [
      {
        slug: "24-soderlund-drive-doncaster",
        address: "24 Soderlund Drive",
        price: 2300000,
        floor: 267,
        land: 690,
        beds: 4,
        baths: 3,
        cars: 2,
      },
    ],
  ),

  ...campaignListings(
    c({
      suburb: "Fraser Rise",
      postcode: "3336",
      type: "house",
      firb: "NO",
      completion: "One-year-new home, ready to settle",
      primary: "Wiyal Primary School",
      secondary: "Springside West Secondary College",
      commission: "$30,000 inc GST, payment at settlement",
      pack: pack.aldo,
    }),
    [
      {
        slug: "7-jermyn-street-fraser-rise",
        address: "Lot 523, 7 Jermyn Street",
        price: 710000,
        floor: 177.1,
        land: 294,
        beds: 4,
        baths: 2,
        cars: 2,
        occupancy: "Leased at $2,390 per month.",
        yieldPercent: monthlyYield(710000, 2390),
        evidenceLine: "Leased $2,390 per month",
      },
    ],
  ),

  ...campaignListings(
    c({
      suburb: "Glen Waverley",
      postcode: "3150",
      type: "house",
      firb: "NO",
      completion: "Established house",
      primary: "Mount View Primary School",
      secondary: "Highvale Secondary College",
      commission: "$40,000 inc GST, payment at settlement",
      pack: pack.almray,
    }),
    [
      {
        slug: "18-almray-place-glen-waverley",
        address: "18 Almray Place",
        price: 1680000,
        floor: 161,
        land: 640,
        beds: 4,
        baths: 2,
        cars: 2,
        occupancy: "Rental advised at $3,900 per month.",
        yieldPercent: monthlyYield(1680000, 3900),
        evidenceLine: "Rent $3,900/month",
      },
    ],
  ),

  ...campaignListings(
    c({
      suburb: "Heidelberg",
      postcode: "3084",
      type: "apartment",
      firb: "NO",
      completion: "Established apartment",
      primary: "Heidelberg Primary School",
      secondary: "Viewbank College",
      commission: "3% inc GST, payment at settlement",
      pack: pack.vine,
    }),
    [
      {
        slug: "1-vine-street-heidelberg-g01",
        address: "G01, 1 Vine Street",
        price: 756000,
        floor: 124,
        beds: 2,
        baths: 2,
        cars: 1,
        specNote: "Internal 73 m² plus 51 m² external.",
        occupancy: "Leased. Passing rent not advised on the list — confirm with the desk.",
      },
      {
        slug: "1-vine-street-heidelberg-g02",
        address: "G02, 1 Vine Street",
        price: 735000,
        floor: 126,
        beds: 2,
        baths: 2,
        cars: 1,
        specNote: "Internal 73 m² plus 53 m² external.",
        occupancy: "Rent advised at $2,933 per month.",
        yieldPercent: monthlyYield(735000, 2933),
        evidenceLine: "Rent $2,933/month",
      },
      {
        slug: "1-vine-street-heidelberg-g03",
        address: "G03, 1 Vine Street",
        price: 750750,
        floor: 120,
        beds: 2,
        baths: 2,
        cars: 1,
        specNote: "Internal 67 m² plus 53 m² external.",
        occupancy: "Rent advised at $2,816 per month.",
        yieldPercent: monthlyYield(750750, 2816),
        evidenceLine: "Rent $2,816/month",
      },
      {
        slug: "1-vine-street-heidelberg-101",
        address: "101, 1 Vine Street",
        price: 945000,
        floor: 114,
        beds: 3,
        baths: 2,
        cars: 2,
        specNote: "Internal 95 m² plus 19 m² external.",
        occupancy: "Vacant possession as advised.",
      },
      {
        slug: "1-vine-street-heidelberg-102",
        address: "102, 1 Vine Street",
        price: 735000,
        floor: 87,
        beds: 2,
        baths: 2,
        cars: 1,
        specNote: "Internal 73 m² plus 14 m² external.",
        occupancy: "Rent advised at $3,042 per month.",
        yieldPercent: monthlyYield(735000, 3042),
        evidenceLine: "Rent $3,042/month",
      },
      {
        slug: "1-vine-street-heidelberg-201",
        address: "201, 1 Vine Street",
        price: 840000,
        floor: 105,
        beds: 2,
        baths: 2,
        cars: 2,
        specNote: "Internal 79 m² plus 26 m² external.",
        occupancy: "Rent advised at $2,911 per month.",
        yieldPercent: monthlyYield(840000, 2911),
        evidenceLine: "Rent $2,911/month",
      },
    ],
  ),

  ...campaignListings(
    c({
      suburb: "Malvern East",
      postcode: "3145",
      type: "townhouse",
      firb: "NO",
      completion: "Established townhouse",
      primary: "Malvern Valley Primary School",
      secondary: "Ashwood High School",
      commission: "$35,000 inc GST, payment at settlement",
      pack: pack.waverley,
    }),
    [
      {
        slug: "547a-waverley-road-malvern-east",
        address: "547A Waverley Road",
        price: 1530000,
        floor: 210,
        land: 193,
        beds: 3,
        baths: 3,
        cars: 2,
        occupancy: "Rent advised at $995 per week.",
        yieldPercent: weeklyYield(1530000, 995),
        evidenceLine: "Rent $995/week",
      },
    ],
  ),

  ...campaignListings(
    c({
      suburb: "Pakenham",
      postcode: "3810",
      type: "house",
      firb: "NO",
      completion: "Established house",
      primary: "Pakenham Primary School",
      secondary: "Pakenham Secondary College",
      commission: "$30,000 inc GST, payment at settlement",
      pack: pack.eildon,
    }),
    [
      {
        slug: "9-eildon-street-pakenham",
        address: "9 Eildon Street",
        price: 810000,
        floor: 184.42,
        land: 560,
        beds: 4,
        baths: 2,
        cars: 2,
        occupancy: "Rent advised at $550 per week.",
        yieldPercent: weeklyYield(810000, 550),
        evidenceLine: "Rent $550/week",
      },
    ],
  ),

  ...campaignListings(
    c({
      suburb: "Thomastown",
      postcode: "3074",
      type: "townhouse",
      firb: "NO",
      completion: "Established townhouse",
      primary: "Thomastown Primary School",
      secondary: "Thomastown Secondary College",
      commission: "3% inc GST, payment at settlement",
      pack: pack.westall,
      extraCampaign: "Also known as 2 Westall Street. Neighbouring units 3 and 4 rents were advised at $2,687 and $2,608 per month.",
    }),
    [
      {
        slug: "321-high-street-thomastown-unit-1",
        address: "Unit 1, 321 High Street",
        status: "sold",
        price: null,
        floor: 130.7,
        beds: 3,
        baths: 2.5,
        cars: 2,
        carNote: "1 + 1",
        specNote: "One living area.",
      },
      {
        slug: "321-high-street-thomastown-unit-2",
        address: "Unit 2, 321 High Street",
        status: "sold",
        price: null,
        floor: 115.6,
        beds: 3,
        baths: 2.5,
        cars: 2,
        carNote: "1 + 1",
        specNote: "One living area.",
      },
      {
        slug: "321-high-street-thomastown-unit-3",
        address: "Unit 3, 321 High Street",
        price: 765000,
        floor: 115.6,
        beds: 3,
        baths: 2.5,
        cars: 2,
        carNote: "1 + 1",
        specNote: "One living area.",
        occupancy: "Rent advised at $2,687 per month for this design.",
        yieldPercent: monthlyYield(765000, 2687),
      },
      {
        slug: "321-high-street-thomastown-unit-4",
        address: "Unit 4, 321 High Street",
        price: 765000,
        floor: 115.9,
        beds: 3,
        baths: 2.5,
        cars: 2,
        carNote: "1 + 1",
        specNote: "One living area.",
        occupancy: "Rent advised at $2,608 per month for this design.",
        yieldPercent: monthlyYield(765000, 2608),
      },
    ],
  ),

  ...campaignListings(
    c({
      suburb: "Beveridge",
      postcode: "3753",
      type: "house",
      firb: "YES",
      completion: "August 2026 — OC ready in two weeks as advised",
      primary: "Beveridge Primary School",
      secondary: "Ngayuk College",
      commission: "$30,000 inc GST, payment at settlement",
      pack: pack.lyra,
    }),
    [
      {
        slug: "22-spafield-road-beveridge",
        address: "Lot 337, 22 Spafield Road",
        price: 675000,
        floor: 185.82,
        land: 313,
        beds: 4,
        baths: 2,
        cars: 2,
      },
    ],
  ),

  ...campaignListings(
    c({
      suburb: "Box Hill South",
      postcode: "3128",
      type: "house",
      firb: "NO",
      completion: "Brand-new luxury house",
      primary: "Roberts McCubbin Primary School",
      secondary: "Box Hill High School",
      commission: "2.2% inc GST, payment at settlement",
      pack: pack.joyhill,
    }),
    [
      {
        slug: "12-joyhill-avenue-box-hill-south",
        address: "12 Joyhill Avenue",
        price: 3150000,
        floor: 467,
        land: 599,
        beds: 5,
        baths: 5.5,
        cars: 2,
      },
    ],
  ),

  ...campaignListings(
    c({
      suburb: "Burwood",
      postcode: "3125",
      type: "townhouse",
      firb: "YES",
      completion: "Newly established duplex, ready to settle",
      primary: "Roberts McCubbin Primary School",
      secondary: "Mount Waverley Secondary College",
      commission: "2% inc GST, payment at settlement",
      pack: pack.christina,
    }),
    [
      {
        slug: "16a-christina-street-burwood",
        address: "16A Christina Street",
        price: 1750000,
        floor: 282.5,
        land: 340.91,
        beds: 4,
        baths: 3.5,
        cars: 2,
        carNote: "1 + 1",
        specNote: "Two living areas plus a study. Price has been adjusted on the current list.",
      },
    ],
  ),

  ...campaignListings(
    c({
      suburb: "Burwood East",
      postcode: "3151",
      type: "house",
      firb: "NO",
      completion: "Q3 2026",
      primary: "Orchard Grove Primary School",
      secondary: "Forest Hill College",
      commission: "3% inc GST, payment at settlement",
      pack: pack.davis,
    }),
    [
      {
        slug: "63-davis-street-burwood-east",
        address: "63 Davis Street",
        price: 3150000,
        floor: 401.03,
        land: 725,
        beds: 5,
        baths: 3.5,
        cars: 2,
        specNote: "Three retreats as advised.",
      },
    ],
  ),

  ...campaignListings(
    c({
      suburb: "Clayton South",
      postcode: "3169",
      type: "townhouse",
      firb: "YES",
      completion: "Q3 2026",
      primary: "Clayton South Primary School",
      secondary: "Westall Secondary College",
      commission: "4% inc GST, payment at settlement",
      pack: pack.mcmillan,
    }),
    [
      {
        slug: "45-mcmillan-street-clayton-south-unit-1",
        address: "Unit 1, 45 McMillan Street",
        price: 1390000,
        floor: 222.42,
        land: 242,
        beds: 4,
        baths: 3,
        cars: 2,
        specNote: "Two living areas. Price adjusted from $1.5 million.",
      },
      {
        slug: "45-mcmillan-street-clayton-south-unit-2",
        address: "Unit 2, 45 McMillan Street",
        price: 1380000,
        floor: 202.61,
        land: 283,
        beds: 4,
        baths: 3,
        cars: 2,
        specNote: "Two living areas.",
      },
      {
        slug: "45-mcmillan-street-clayton-south-unit-3",
        address: "Unit 3, 45 McMillan Street",
        price: 1288000,
        floor: 201.41,
        land: 178,
        beds: 3,
        baths: 3,
        cars: 2,
        specNote: "Two living areas.",
      },
      {
        slug: "45-mcmillan-street-clayton-south-unit-4",
        address: "Unit 4, 45 McMillan Street",
        price: 1280000,
        floor: 184.92,
        land: 185,
        beds: 3,
        baths: 2.5,
        cars: 2,
        specNote: "One living area.",
      },
    ],
  ),

  ...campaignListings(
    c({
      suburb: "Cranbourne East",
      postcode: "3977",
      type: "house",
      firb: "YES",
      completion: "Newly established house",
      primary: "Casey Fields Primary School",
      secondary: "Cranbourne Secondary College",
      commission: "$30,000 inc GST, payment at settlement",
      pack: pack.nelson,
    }),
    [
      {
        slug: "16-talc-street-cranbourne-east",
        address: "Lot 33, 16 Talc Street",
        price: 840000,
        floor: 183.15,
        land: 315,
        beds: 4,
        baths: 3.5,
        cars: 2,
        carNote: "1 + 1",
        specNote: "Study included. Rent appraisal advised at $650–$700 per week.",
      },
      {
        slug: "18-talc-street-cranbourne-east",
        address: "Lot 32, 18 Talc Street",
        status: "under-offer",
        price: null,
        floor: 187.19,
        land: 315,
        beds: 4,
        baths: 3.5,
        cars: 2,
        carNote: "1 + 1",
        specNote: "Study included. Under contract.",
      },
      {
        slug: "20-talc-street-cranbourne-east",
        address: "Lot 31, 20 Talc Street",
        status: "under-offer",
        price: null,
        floor: 187.19,
        land: 315,
        beds: 4,
        baths: 3.5,
        cars: 2,
        carNote: "1 + 1",
        specNote: "Study included. Under contract.",
      },
      {
        slug: "22-talc-street-cranbourne-east",
        address: "Lot 30, 22 Talc Street",
        price: 840000,
        floor: 183.15,
        land: 315,
        beds: 4,
        baths: 3.5,
        cars: 2,
        carNote: "1 + 1",
        specNote: "Study included. Rent appraisal advised at $650–$700 per week.",
      },
    ],
  ),

  ...campaignListings(
    c({
      suburb: "Deanside",
      postcode: "3336",
      type: "house",
      firb: "YES",
      completion: "August 2026 — OC awaiting OP, completion August 2026",
      primary: "Deanside Primary School",
      secondary: "Springside West Secondary College",
      commission: "$30,000 inc GST, payment at settlement",
      pack: pack.sunrise,
    }),
    [
      {
        slug: "6-elvira-place-deanside",
        address: "Lot 251, 6 Elvira Place",
        price: 750000,
        floor: 203.27,
        land: 294,
        beds: 4,
        baths: 2,
        cars: 2,
        specNote: "Four bedrooms plus lounge.",
      },
      {
        slug: "5-isla-avenue-deanside",
        address: "Lot 260, 5 Isla Avenue",
        price: 750000,
        floor: 203.2,
        land: 294,
        beds: 4,
        baths: 2,
        cars: 2,
        specNote: "Four bedrooms plus lounge.",
      },
      {
        slug: "7-isla-avenue-deanside",
        address: "Lot 261, 7 Isla Avenue",
        price: 750000,
        floor: 201.78,
        land: 294,
        beds: 4,
        baths: 2,
        cars: 2,
        specNote: "Four bedrooms plus lounge.",
      },
      {
        slug: "27-lanning-way-deanside",
        address: "Lot 326, 27 Lanning Way",
        price: 750000,
        floor: 203.73,
        land: 294,
        beds: 4,
        baths: 3,
        cars: 2,
        specNote: "Four bedrooms plus lounge.",
      },
    ],
  ),

  ...campaignListings(
    c({
      suburb: "Doncaster",
      postcode: "3108",
      type: "house",
      firb: "NO",
      completion: "Brand-new house",
      primary: "Doncaster Primary School",
      secondary: "Doncaster Secondary College",
      commission: "$80,000 inc GST, payment at settlement",
      pack: pack.walker,
    }),
    [
      {
        slug: "32-walker-street-doncaster",
        address: "32 Walker Street",
        price: 3850000,
        floor: 557,
        land: 748,
        beds: 5,
        baths: 5,
        cars: 2,
        specNote: "Three living areas and a theatre room.",
      },
    ],
  ),

  ...campaignListings(
    c({
      suburb: "Doncaster",
      postcode: "3108",
      type: "house",
      firb: "NO",
      completion: "Newly established single-level house",
      primary: "Templestowe Heights Primary School",
      secondary: "Templestowe College",
      commission: "2% inc GST, payment at settlement",
      pack: pack.manningham,
    }),
    [
      {
        slug: "413-manningham-road-doncaster",
        address: "413 Manningham Road",
        price: 2450000,
        floor: 285.55,
        land: 652,
        beds: 4,
        baths: 3,
        cars: 2,
        specNote: "Two retreats. Also listed on realestate.com.au by Axtra.",
      },
    ],
  ),

  ...campaignListings(
    c({
      suburb: "Doncaster East",
      postcode: "3109",
      type: "townhouse",
      firb: "YES",
      completion: "Newly established townhouse",
      primary: "Doncaster Gardens Primary School",
      secondary: "East Doncaster Secondary College",
      commission: "3% inc GST, payment at settlement",
      pack: pack.major,
    }),
    [
      {
        slug: "2-major-street-doncaster-east-unit-1",
        address: "Unit 1, 2 Major Street",
        price: 1260000,
        floor: 219,
        beds: 4,
        baths: 3,
        cars: 2,
        specNote: "Two living areas.",
      },
      {
        slug: "2-major-street-doncaster-east-unit-4",
        address: "Unit 4, 2 Major Street",
        price: 1198000,
        floor: 170,
        beds: 4,
        baths: 3,
        cars: 2,
        specNote: "Two living areas.",
      },
      {
        slug: "2-major-street-doncaster-east-unit-5",
        address: "Unit 5, 2 Major Street",
        price: 1360000,
        floor: 209.9,
        beds: 4,
        baths: 3.5,
        cars: 2,
        specNote: "Two living areas.",
      },
    ],
  ),

  ...campaignListings(
    c({
      suburb: "Fraser Rise",
      postcode: "3336",
      type: "house",
      firb: "YES",
      completion: "Newly established house",
      primary: "Wiyal Primary School",
      secondary: "Springside West Secondary College",
      commission: "$30,000 inc GST, payment at settlement",
      pack: pack.mercury,
    }),
    [
      {
        slug: "lot-218-6-mercury-avenue-fraser-rise",
        address: "Lot 218, 6 Mercury Avenue",
        status: "under-offer",
        price: null,
        floor: 177.3,
        land: 262,
        beds: 4,
        baths: 2,
        cars: 2,
        specNote: "Under contract. Last advised asking price was $715,000 after a price adjustment.",
      },
    ],
  ),

  ...campaignListings(
    c({
      suburb: "Fraser Rise",
      postcode: "3336",
      type: "house",
      firb: "YES",
      completion: "Q3 2026, one-part contract house",
      primary: "Wiyal Primary School",
      secondary: "Springside West Secondary College",
      commission: "$30,000 inc GST, payment at settlement",
      pack: pack.parkglen,
    }),
    [
      {
        slug: "11-granite-crescent-fraser-rise",
        address: "Lot 148, 11 Granite Crescent",
        status: "sold",
        price: null,
        floor: 189.78,
        land: 312,
        beds: 4,
        baths: 2.5,
        cars: 2,
        specNote: "Four bedrooms plus lounge. Rent appraisal $550–$600 per week.",
      },
      {
        slug: "26-granite-crescent-fraser-rise",
        address: "Lot 159, 26 Granite Crescent",
        status: "under-offer",
        price: null,
        floor: 177.33,
        land: 262,
        beds: 4,
        baths: 2.5,
        cars: 2,
      },
      {
        slug: "8-fossil-way-fraser-rise",
        address: "Lot 314, 8 Fossil Way",
        price: 640000,
        floor: 121.79,
        land: 178,
        beds: 3,
        baths: 2,
        cars: 2,
        carNote: "1 + 1",
        specNote: "Estimated completion September 2026.",
      },
      {
        slug: "7-fossil-way-fraser-rise",
        address: "Lot 315, 7 Fossil Way",
        price: 640000,
        floor: 131.8,
        land: 187,
        beds: 3,
        baths: 2,
        cars: 2,
        carNote: "1 + 1",
        specNote: "Advised as brand new.",
      },
    ],
  ),

  ...campaignListings(
    c({
      suburb: "Mount Waverley",
      postcode: "3149",
      type: "townhouse",
      firb: "YES",
      completion: "Newly established townhouse",
      primary: "Syndal South Primary School",
      secondary: "Mount Waverley Secondary College",
      commission: "3% inc GST, payment at settlement",
      pack: pack.wingate,
    }),
    [
      {
        slug: "12-wingate-avenue-mount-waverley-unit-1",
        address: "Unit 1, 12 Wingate Avenue",
        reserved: true,
        price: null,
        floor: 202.3,
        land: 268,
        beds: 4,
        baths: 3.5,
        cars: 2,
        specNote: "One living area. Price has been adjusted. Currently reserved.",
      },
      {
        slug: "12-wingate-avenue-mount-waverley-unit-3",
        address: "Unit 3, 12 Wingate Avenue",
        price: 1650000,
        floor: 191.3,
        land: 233,
        beds: 4,
        baths: 3,
        cars: 2,
        specNote: "One living area.",
      },
    ],
  ),
];
